-define(PLURALS, [
	{<<"ach">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"af">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ak">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"am">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"an">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"anp">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ar">>,
		<<"nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);">>,
		6},
	{<<"arn">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"as">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ast">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ay">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"az">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"be">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"bg">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"bn">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"bo">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"br">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"brx">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"bs">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"ca">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"cgg">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"cs">>, <<"nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;">>, 3},
	{<<"csb">>,
		<<"nplurals=3; plural=(n==1) ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;">>,
		3},
	{<<"cy">>,
		<<"nplurals=4; plural=(n==1) ? 0 : (n==2) ? 1 : (n != 8 && n != 11) ? 2 : 3;">>,
		4},
	{<<"da">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"de">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"doi">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"dz">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"el">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"en">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"eo">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"es">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"es_AR">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"et">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"eu">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"fa">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"ff">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"fi">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"fil">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"fo">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"fr">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"fur">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"fy">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ga">>,
		<<"nplurals=5; plural=n==1 ? 0 : n==2 ? 1 : (n>2 && n<7) ? 2 :(n>6 && n<11) ? 3 : 4;">>,
		5},

	{<<"gd">>,
		<<"nplurals=4; plural=(n==1 || n==11) ? 0 : (n==2 || n==12) ? 1 : (n > 2 && n < 20) ? 2 : 3;">>,
		4},
	{<<"gl">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"gu">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"gun">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"ha">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"he">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"hi">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"hne">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"hr">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"hu">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"hy">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ia">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"id">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"is">>, <<"nplurals=2; plural=(n%10!=1 || n%100==11);">>, 2},
	{<<"it">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ja">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"jbo">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"jv">>, <<"nplurals=2; plural=(n != 0);">>, 2},
	{<<"ka">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"kk">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"kl">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"km">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"kn">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ko">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"ku">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"kw">>,
		<<"nplurals=4; plural=(n==1) ? 0 : (n==2) ? 1 : (n == 3) ? 2 : 3;">>, 4},
	{<<"ky">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"lb">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ln">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"lo">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"lt">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"lv">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2);">>, 3},
	{<<"mai">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"mfe">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"mg">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"mi">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"mk">>, <<"nplurals=2; plural= n==1 || n%10==1 ? 0 : 1">>, 2},
	{<<"ml">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"mn">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"mni">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"mnk">>, <<"nplurals=3; plural=(n==0 ? 0 : n==1 ? 1 : 2);">>, 3},
	{<<"mr">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ms">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"mt">>,
		<<"nplurals=4; plural=(n==1 ? 0 : n==0 || ( n%100>1 && n%100<11) ? 1 : (n%100>10 && n%100<20 ) ? 2 : 3);">>,
		4},
	{<<"my">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"nah">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"nap">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"nb">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ne">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"nl">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"nn">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"no">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"nso">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"oc">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"or">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"pa">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"pap">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"pl">>,
		<<"nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"pms">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ps">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"pt">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"pt_BR">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"rm">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ro">>,
		<<"nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2);">>,
		3},
	{<<"ru">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"rw">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sah">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"sat">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sco">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sd">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"se">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"si">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sk">>, <<"nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;">>, 3},
	{<<"sl">>,
		<<"nplurals=4; plural=(n%100==1 ? 1 : n%100==2 ? 2 : n%100==3 || n%100==4 ? 3 : 0);">>,
		4},
	{<<"so">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"son">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sq">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sr">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"su">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"sv">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"sw">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"ta">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"te">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"tg">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"th">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"ti">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"tk">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"tr">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"tt">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"ug">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"uk">>,
		<<"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);">>,
		3},
	{<<"ur">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"uz">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"vi">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"wa">>, <<"nplurals=2; plural=(n > 1);">>, 2},
	{<<"wo">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"yo">>, <<"nplurals=2; plural=(n != 1);">>, 2},
	{<<"zh">>, <<"nplurals=1; plural=0;">>, 1},
	{<<"zh">>, <<"nplurals=2; plural=(n > 1);">>, 2}

]).
